// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sptahvlzkrktypbcsrwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwdGFodmx6a3JrdHlwYmNzcnd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODIzNDIsImV4cCI6MjA3NDU1ODM0Mn0.sIiRjmm1zWFLsqCM0p1lvHSZtwEIt0NhiBqij8u699Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});